### ISSUE TITLE
Texts created via the UI can't be edited

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#204] opened 2015-10-16 23:05 UTC
See: http://wustl.curationexperts.com/concern/texts/8k71nh25j
and 
http://wustl.curationexperts.com/concern/texts/4m90dv58z

**Comment by jcoyne** [comment] 2015-10-17 03:48
Solr is refusing the connection:

```
Blacklight::Exceptions::ECONNREFUSED (Connection refused - Unable to connect to Solr instance using #<RSolr::Client:0x007f577b4e0898 @uri=#<URI::HTTP http://127.0.0.1:8080/hydra/>, @proxy=nil, @connection=#<RSolr::Connection:0x007f577b4e08c0 @http=#<Net::HTTP 127.0.0.1:8080 open=false>>, @options={:url=>"http://127.0.0.1:8080/hydra"}>: #<Errno::ECONNREFUSED: Connection refused

  blacklight (5.15.0) lib/blacklight/solr_repository.rb:53:in `rescue in send_and_receive'
  blacklight (5.15.0) lib/blacklight/solr_repository.rb:42:in `send_and_receive'
  blacklight (5.15.0) lib/blacklight/solr_repository.rb:28:in `search'
  blacklight (5.15.0) lib/blacklight/search_helper.rb:109:in `search_results'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-227318ecb609/app/controllers/concerns/curation_concerns/curation_concern_controller.rb:50:in `block (2 levels) in show'
  actionpack (4.2.4) lib/action_controller/metal/mime_responds.rb:217:in `call'
  actionpack (4.2.4) lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
  /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-227318ecb609/app/controllers/concerns/curation_concerns/curation_concern_controller.rb:48:in `show'
```

**Comment by jcoyne** [comment] 2015-10-17 03:52
I'm seeing that every page is in error right now:

Even this page won't draw due to the same error:
http://wustl.curationexperts.com/catalog?utf8=%E2%9C%93&search_field=all_fields&q=

is solr down?

**Comment by jcoyne** [comment] 2015-10-19 16:30
Can't attempt to duplicate until the server is back.

**Comment by jcoyne** [comment] 2015-10-19 22:30
I believe this to be a duplicate of #198 and you should be fixed on the server.  The fix is in the import process, so the existing records will have to be recreated in order to confirm the fix.

**Comment by mark-dce** [comment] 2015-10-20 19:26
Still happening after rebuild and redeploy.
See: http://wustl.curationexperts.com/concern/texts/mp48sc763

**Comment by jcoyne** [comment] 2015-10-20 19:27
```
t = Text.find('mp48sc763')
t.member_ids
TypeError: no implicit conversion from nil to integer
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:57:in `delete_at'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:57:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:26:in `ids_reader'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/builder.rb:18:in `block in define_readers'
```

**Comment by jcoyne** [comment] 2015-10-20 19:37
Proxies don't all have next.

```
=> [{"id"=>"mp48sc763/members/bf16a8d2-bf4f-4346-8955-483a598bff40"}, {"id"=>"mp48sc763/members/c0fabcb3-ccc0-4500-834d-e6a0359b1932", "next_ssim"=>["mp48sc763/members/bf16a8d2-bf4f-4346-8955-483a598bff40"]}, {"id"=>"mp48sc763/members/47a89ef0-4c9c-4555-b758-a5f1d628bfc3", "next_ssim"=>["mp48sc763/members/e05347fd-bbd8-40ff-8aa0-bc27688d29d2"]}, {"id"=>"mp48sc763/members/e05347fd-bbd8-40ff-8aa0-bc27688d29d2"}, {"id"=>"mp48sc763/members/fa8b67a3-ce43-4a48-bb2f-8ded2d2d61d6"}, {"id"=>"mp48sc763/members/c74936c8-3f7d-42b4-a372-7b4be46f9b7e", "next_ssim"=>["mp48sc763/members/8892cac5-4fa5-42ab-b975-644a27aaeba7"]}, {"id"=>"mp48sc763/members/fbc93710-a25e-4782-8172-2edd3cf1b093"}, {"id"=>"mp48sc763/members/8892cac5-4fa5-42ab-b975-644a27aaeba7", "next_ssim"=>["mp48sc763/members/fbc93710-a25e-4782-8172-2edd3cf1b093"]}]
```

**Comment by mark-dce** [comment] 2015-10-20 21:07
Still happening - see http://wustl.curationexperts.com/concern/texts/5t34sj61p/edit

**Comment by jcoyne** [comment] 2015-10-20 21:14
```
t.association(:members).send(:load_proxies_from_solr).map { |s| s.slice('id', 'next_ssim') }
=> [{"id"=>"5t34sj61p/members/b09cc1d2-df80-49b7-98e0-8afc14950fb7", "next_ssim"=>["5t34sj61p/members/061ca982-9e95-4b95-ac09-385ebef7f147"]}, {"id"=>"5t34sj61p/members/061ca982-9e95-4b95-ac09-385ebef7f147", "next_ssim"=>["5t34sj61p/members/0e1c6d18-6c62-4a7e-b614-e52b8eb09d70"]}, {"id"=>"5t34sj61p/members/0e1c6d18-6c62-4a7e-b614-e52b8eb09d70", "next_ssim"=>["5t34sj61p/members/3ac2e967-6696-4596-b90f-bd79f9fa7bd7"]}, {"id"=>"5t34sj61p/members/f761ad62-d59b-4a59-8f7c-e7845e37b987"}, {"id"=>"5t34sj61p/members/3ac2e967-6696-4596-b90f-bd79f9fa7bd7", "next_ssim"=>["5t34sj61p/members/325ee69f-9c72-4c54-93f1-cbd12960fbcc"]}, {"id"=>"5t34sj61p/members/6f61536a-d1e0-4724-814f-f0fa74c80959", "next_ssim"=>["5t34sj61p/members/fcfcf732-d443-4216-a809-021eeb1c5bbd"]}, {"id"=>"5t34sj61p/members/fcfcf732-d443-4216-a809-021eeb1c5bbd"}, {"id"=>"5t34sj61p/members/c366066e-c759-4a90-8ed8-00848736959b"}, {"id"=>"5t34sj61p/members/325ee69f-9c72-4c54-93f1-cbd12960fbcc", "next_ssim"=>["5t34sj61p/members/8a8b934b-9b39-43ca-a73f-68c8bf7dc6c5"]}, {"id"=>"5t34sj61p/members/8a8b934b-9b39-43ca-a73f-68c8bf7dc6c5"}]
```

**Comment by mark-dce** [comment] 2015-10-20 21:26
Appears not to happen if I upload/attach each file individually: http://wustl.curationexperts.com/concern/texts/kh04dp73w

**Closed as completed** 2015-10-26 13:38 UTC
Labels: bug
