### ISSUE TITLE
Files list on a work should clearly identify when there are additional attachments

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#86] opened 2015-08-31 23:14 UTC
**CURRENT BEHAVIOR**
The scrollbar is hidden until I hover over the the frame, and I can't tell visually that there are actually three files attached to the work shown below.  Sample object http://wustl.curationexperts.com/concern/videos/sq87bt605

**ACCEPTANCE**
- [ ] Show the scrollbar if the list is clipped, or let the counting box expand so additional items aren't clipped, or do something else so it's clear when an object has more than one file attachment.

**WHAT DISPLAYS** (it looks like there's only one file because there's no scroll bar or any other indication that information is being clipped)
<img width="1170" alt="wustl 086 - file attachments - intial display" src="https://cloud.githubusercontent.com/assets/3064318/9592815/8e64e3cc-500c-11e5-8fdc-059e060b0c90.png">

**WHAT IS HIDDEN** (but there's really three, but you have to scroll over them to discover them)
<img width="1158" alt="wustl 086 - file attachments - there but clipped" src="https://cloud.githubusercontent.com/assets/3064318/9592824/b3a47e40-500c-11e5-9cb9-d96a71efef9e.png">

**Comment by jcoyne** [comment] 2015-09-01 20:21
https://github.com/projecthydra-labs/curation_concerns/issues/254

**Comment by val99erie** [comment] 2015-09-14 15:58
@mark-dce I'm not able to reproduce the problem.  When I use either firefox or chrome, I see the files window with a scrollbar clearly showing.  Maybe I'm not reproducing it properly?  The sample object that you listed above seems to not exist in the sandbox anymore.  Is there another sample object that has this problem?  Or perhaps the scrollbar has been fixed in one of the gems that we upgraded?

**Comment by mark-dce** [comment] 2015-09-14 20:48
@val99erie - the problem is partially fixed by having made the thumbnails smaller, but I still don't see a scrollbar in firefox, safari, or chrome.  The only indication I get is the half-displayed item, the scrollbar only appears if I click in the file list and try to scroll.

**FIREFOX 40.0.3**
<img width="1063" alt="wustl 086 - file attachments - no scrollbar firefox" src="https://cloud.githubusercontent.com/assets/3064318/9861431/e8ca587e-5af7-11e5-909c-55351f97fc25.png">

**Comment by mark-dce** [comment] 2015-09-15 17:46
Scrollbars are a function of system preference setting in OS X.  See **System Preferences**, **General**, **Show Scroll Bars**.  Note that the default behavior for _auto_ changes in Yosemite to hide scrollbars in most cases.

**Closed as completed** 2015-09-15 17:46 UTC
Labels: question
